set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR c6000)

set(TI_DIR "C:/TI/c6000_7.4.24")

set(CMAKE_C_COMPILER "${TI_DIR}/bin/cl6x.exe")
set(CMAKE_CXX_COMPILER "${TI_DIR}/bin/cl6x.exe")

# --- THE FIX ---
set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_CXX_COMPILER_WORKS TRUE)
