name: Build Roomove (AAX)
on: [push]

jobs:
  build-windows:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure CMake
        run: |
          cmake -B build -G "Visual Studio 17 2022" -A x64 `
          -DAAX_SDK_PATH="${{ env.AAX_SDK_PATH }}" `
          -DCMAKE_BUILD_TYPE=Release

      - name: Build AAX Binary
        run: cmake --build build --config Release --target Roomove_AAX
